// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYGwDiNuLes4yyZ7tlJW2-RWuaNmJ7vEA',
    appId: '1:168944673103:web:13ec3e2d6cb2c90536653a',
    messagingSenderId: '168944673103',
    projectId: 'stok-satis-takips',
    authDomain: 'stok-satis-takips.firebaseapp.com',
    storageBucket: 'stok-satis-takips.firebasestorage.app',
    measurementId: 'G-V0EEN3RKQK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEHa5JvxifYkyGcQDm8avDjTpUr2LOJSs',
    appId: '1:168944673103:android:430e6bcfcbe193cd36653a',
    messagingSenderId: '168944673103',
    projectId: 'stok-satis-takips',
    storageBucket: 'stok-satis-takips.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWhiD8FtuU1_6LK5-nKy_0yI7ByJdbHwU',
    appId: '1:168944673103:ios:ab94c2570b7361e936653a',
    messagingSenderId: '168944673103',
    projectId: 'stok-satis-takips',
    storageBucket: 'stok-satis-takips.firebasestorage.app',
    iosBundleId: 'com.cilginpenguen.stokSatisFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYGwDiNuLes4yyZ7tlJW2-RWuaNmJ7vEA',
    appId: '1:168944673103:web:0018039f2e5e4b8536653a',
    messagingSenderId: '168944673103',
    projectId: 'stok-satis-takips',
    authDomain: 'stok-satis-takips.firebaseapp.com',
    storageBucket: 'stok-satis-takips.firebasestorage.app',
    measurementId: 'G-D05EMH1FFR',
  );
}
